/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;

/**
 *
 * @author ELIZEU
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTema = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelSobrenome = new javax.swing.JLabel();
        jLabelNascimento = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldCPF1 = new javax.swing.JTextField();
        jTextFieldCPF2 = new javax.swing.JTextField();
        jTextFieldCPF3 = new javax.swing.JTextField();
        jTextFieldCPF4 = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelFundoCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));

        jLabelTema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTema.setText("Gerenciamento de Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTema)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTema)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 450, 40);

        jLabelCPF.setText("CPF:");
        getContentPane().add(jLabelCPF);
        jLabelCPF.setBounds(40, 80, 60, 14);

        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(40, 120, 60, 14);

        jLabelSobrenome.setText("Sobrenome:");
        getContentPane().add(jLabelSobrenome);
        jLabelSobrenome.setBounds(40, 160, 60, 14);

        jLabelNascimento.setText("Nascimento:");
        getContentPane().add(jLabelNascimento);
        jLabelNascimento.setBounds(40, 200, 60, 14);

        jLabelSexo.setText("Sexo:");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(40, 240, 60, 14);

        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF);
        jTextFieldCPF.setBounds(150, 150, 190, 30);

        jTextFieldCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF1);
        jTextFieldCPF1.setBounds(150, 190, 190, 30);

        jTextFieldCPF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF2);
        jTextFieldCPF2.setBounds(150, 110, 190, 30);

        jTextFieldCPF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF3);
        jTextFieldCPF3.setBounds(150, 230, 190, 30);

        jTextFieldCPF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF4);
        jTextFieldCPF4.setBounds(150, 70, 190, 30);

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar);
        Salvar.setBounds(140, 300, 63, 23);

        jButtonNovo.setText("Novo");
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(220, 300, 57, 23);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(290, 300, 51, 23);

        jLabelFundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundotelaLogin.png"))); // NOI18N
        getContentPane().add(jLabelFundoCadastro);
        jLabelFundoCadastro.setBounds(-6, 0, 500, 350);

        setSize(new java.awt.Dimension(510, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jTextFieldCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF1ActionPerformed

    private void jTextFieldCPF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF2ActionPerformed

    private void jTextFieldCPF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF3ActionPerformed

    private void jTextFieldCPF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF4ActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        JOptionPane.showMessageDialog(rootPane, " Cadastrado com sucesso! " );
    }//GEN-LAST:event_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salvar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelFundoCadastro;
    private javax.swing.JLabel jLabelNascimento;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCPF1;
    private javax.swing.JTextField jTextFieldCPF2;
    private javax.swing.JTextField jTextFieldCPF3;
    private javax.swing.JTextField jTextFieldCPF4;
    // End of variables declaration//GEN-END:variables
}
